version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: uca
    environment:
      POSTGRES_USER: uca
      POSTGRES_PASSWORD: uca
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: